version: '3.7'
#
services:
  iris:
    build:
      context: ./build
      args:
        COMMIT_ID: ${COMMIT_ID}
    hostname: iris
    command: --ISCAgent false --monitorCPF false
    ports:
    # superserver default port 
    - "1972:1972"
    # webserver/management portal port
    - "52773:52773"

    volumes:
    # ISC = InterSystems IRIS install dir
    - ./UserCPF:/home/irisowner/cpf

    environment:
    - TZ=JST-9
